version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  counter:
    depends_on:
      - mongo
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb://mongo:27017/
volumes:
  mongo: