version: '2'

services:
  mongocounter:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  counter:
    depends_on:
      - mongocounter
    build: .
    ports:
      - 5000:5000
volumes:
  mongo: